name: Build macOS App (.app)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller python-docx

      - name: Build macOS .app
        run: |
          pyinstaller main.py \
            --name "PhieuXuatApp" \
            --windowed \
            --icon=unnamed.icns \
            --add-data "PHIEU_TEMPLATE.docx:."

      - name: List dist output
        run: ls -R dist

      - name: Upload macOS .app
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: dist/PhieuXuatApp.app
